services:

  os-image-processor:
    build: ./os-image-processor
    #command: tail -f /dev/null
    cap_drop:
      - ALL
    volumes:
      - ./meta.json:/data/meta.json  # Bind mount the meta.json from host to container
      - unpacked-iso:/data/unpacked-iso
      - download:/data/download
    environment:
      METADATA_FILE: /data/meta.json
      UNPACKED_ISO_DIR: /data/unpacked-iso

  dnsmasq:
    build: ./dnsmasq
    network_mode: host
    # command: tail -f /dev/null
    cap_drop:
      - ALL
    cap_add:
      - CAP_NET_BIND_SERVICE
      - CAP_NET_RAW
      - CAP_NET_ADMIN
    restart: unless-stopped
    volumes:
      - ./meta.json:/data/meta.json:ro  # Bind mount the meta.json from host to container
      - unpacked-iso:/data/unpacked-iso:ro
    environment:
      METADATA_FILE: /data/meta.json
      UNPACKED_ISO_DIR: /data/unpacked-iso

  lighttp:
    build: ./lighttp
    network_mode: host
    # command: tail -f /dev/null
    cap_drop:
      - ALL
    cap_add:
      - CAP_NET_BIND_SERVICE
    restart: unless-stopped
    volumes:
      - unpacked-iso:/data/unpacked-iso:ro
    environment:
      UNPACKED_ISO_DIR: /data/unpacked-iso
    tmpfs:
      - /tmp

volumes:
  unpacked-iso:
  download:
